apiVersion: v1
kind: Service
metadata:
  name: organization-worker-nosql
spec:
  selector:
    app: organization-worker-nosql
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
