apiVersion: apps/v1
kind: Deployment
metadata:
  name: organization-api-nosql
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: organization-api-nosql
  template:
    metadata:
      labels:
        app: organization-api-nosql
    spec:
      containers:
      - image: 751111534101.dkr.ecr.ap-southeast-1.amazonaws.com/dotnetnosql-api:latest-4d30d1269aac6cc6f1c33f53f343802174649175
        name: organization-api-nosql
        env:
          - name: Application__ConnectionString
            valueFrom:
              secretKeyRef:
                name: organizationsecret-api
                key: databaseconnectionstring
          - name: Application__ReadOnlyConnectionString
            valueFrom:
              secretKeyRef:
                name: organizationsecret-api
                key: ReadOnlyConnectionString
          - name: Application__AmazonSQSConfigurationOptions__accessKey
            valueFrom:
              secretKeyRef:
                name: organizationsecret-api
                key: SQSAccessKey
          - name: Application__AmazonSQSConfigurationOptions__secretKey
            valueFrom:
              secretKeyRef:
                name: organizationsecret-api
                key: SQSSecretKey
          - name: Application__AmazonSQSConfigurationOptions__sqsQueueUrl
            valueFrom:
              secretKeyRef:
                name: organizationsecret-api
                key: SQSQueueUrl
          - name: Application__AmazonS3ConfigurationOptions__accessKey
            valueFrom:
              secretKeyRef:
                name: organizationsecret-api
                key: S3AccessKey
          - name: Application__AmazonS3ConfigurationOptions__secretKey
            valueFrom:
              secretKeyRef:
                name: organizationsecret-api
                key: S3secretKey
        ports:
        - containerPort: 80
